name: Upload static assets
on: workflow_dispatch
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Google Cloud Authentication with service account
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCS_SA_KEY }}'

      - name: Verify authentication
        run: gcloud auth application-default print-access-token

      - name: Test GCS access
        run: gsutil ls gs://static.saoladigital.com/
