name: Upload static assets
on: workflow_dispatch
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Authenticate with GCS
        run: |
          echo '${{ secrets.GCS_SA_KEY }}' > /tmp/gcloud-key.json
          gcloud auth activate-service-account --key-file=/tmp/gcloud-key.json

      - name: Install dependencies
        run: npm install

      - name: Build production
        run: npm run build

      # - name: list authentication
      #   run: gcloud auth list

      - name: Upload static assets
        run: npm run upload

      - name: Google Cloud Authentication with service account
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.AR_SA_KEY }}'

      # - name: Print
      #   run: |
      #     echo '${{ toJSON(github) }}'

      - name: Config Docker by Google Cloud
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

      - name: Set Docker build and Artifact Registry variables
        run: |
          echo "ARTIFACT_IMAGE_PATH=${{ secrets.GCP_REGION }}-docker.pkg.dev/${{secrets.GCP_PROJECT_ID}}/${{secrets.GCP_ARTIFACT_REPO}}/en-vocab-client" >> $GITHUB_ENV
          # echo "ARTIFACT_IMAGE_TAG"=${{ github.ref_name }} >> $GITHUB_ENV
          # echo "PAT=${{secrets.PAT}}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          DOCKER_BUILD_TAG=$ARTIFACT_IMAGE_PATH:v1.0.9
          docker build --secret id=github_pat,env=GITHUB_PAT -t $DOCKER_BUILD_TAG .
        env:
          GITHUB_PAT: ${{ secrets.PAT }}

      - name: Push Docker image to Artifact Registry
        run: |
          DOCKER_BUILD_TAG=$ARTIFACT_IMAGE_PATH:v1.0.9
          docker push $DOCKER_BUILD_TAG
